image: docker:latest
services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
- build
- package

build:
  image: openjdk:8-jdk-slim
  stage: build
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    paths:
    - .gradle/wrapper
    - .gradle/caches
  script:
  - ./gradlew assemble
  - cp ./LavalinkServer/build/libs/Lavalink.jar ./LavalinkServer/docker/Lavalink.jar
  artifacts:
    expire_in: 1 week
    paths:
    - LavalinkServer/docker/Lavalink.jar

package:
  stage: package
  script:
  - cd ./LavalinkServer/docker
  - docker build -t registry.gitlab.com/juniperbot/lavalink:$CI_COMMIT_REF_NAME -t registry.gitlab.com/juniperbot/lavalink:$CI_PIPELINE_IID .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/juniperbot/lavalink:$CI_COMMIT_REF_NAME
  - docker push registry.gitlab.com/juniperbot/lavalink:$CI_PIPELINE_IID
  dependencies:
  - build
  only:
  - master-jb
  - dev-jb
